service: serverless-hello-world
frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /hello
